version: '3.8'

services: 
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_PASSWORD: 'testpassword'
      POSTGRES_USER: 'testuser'
    volumes:
      - db_data-1:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend

volumes:
  db_data-1: