name: eitan-workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build the docker-compose
        run: docker-compose up -d --build

      - name: Check running containers
        run: docker ps

      - name: Wait for backend to be available
        run: |
          until curl -sSf http://localhost:5001; do
            echo "Waiting for backend to start..."
            sleep 5
          done

      - name: Show logs for debugging
        run: docker-compose logs