name: eitan-workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
            
      - name: Build the docker-compose
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

      - name: Wait for backend to be available
        run: |
          until curl -sSf http://localhost:5001; do
            echo "Waiting for backend to start..."
            sleep 5
          done

      - name: Show logs for debugging
        run: docker-compose logs