name: eitans workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
        time: '60s'

      - name: Check running containers
        run: docker ps

      - name: run curl test
        run: curl localhost:5001